### ISSUE TITLE
Target Variable explicitly put inside Model function

### ISSUE THREAD

**Issue by nandakallugjeri** [pmaletic/bmarketing#1]
The 'model' function creates a model always using variable called 'y' in the dataframe passed as a parameter. The function has a parameter called target_name, for this purpose, but it doesn't use it. 
So the function call fails when it is called with a dataframe that doesn't have a variable called 'y'.

Error:  Error in eval(predvars, data, env) : object 'y' not found 

code wrong:  dt_model<- rpart(**_y_** ~ ., data = input_data)

**Comment by pmaletic** [comment]
it is flexibile now
